### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by schollz** [schollz/anonfiction#1]
- [x] Add meta tags
- [x] Add icon
- [x] Add description ( Story description > Topic description > Site description)
- [x] Google Webmaster
- [x] Google analytics
- [x] Add RSS (see [Hugo's RSS](https://gohugo.io/templates/rss/#the-embedded-rss-xml))
- [x] Sitemap 
- [x] Change API for /read to `/read/story/X` or `/read/topic/page-1` or `/read/keyword/page-1`
- [x] Show number of pages on `/read`, like "page 1 of 3"
- [x] Change API for write to `/write/X` and add drop-down menu to select the topic (and add it to the form)
- [x] fix description box width in Mobile
- [x] remove bar above curated on about page
- [x] add the story info on the info message for messages (so submitting will still give a link)
- [x] Use random strings for the story ID, they are shorter
- [ ] Limit the number of emails per IP address per hour?
- [x] On profile, after "Your Profile", add checkbox for "Monthly updates when a new issue is published", an email input with the current email, and a button to "Update Preferences"
- [x] Change favicon to black / dark grey
- [x] Add DateCreated and DatePublished to the story to help with RSS (RSS sorts by DatePublished)
- [x] Add links to the stories quotes on the landing page
- [x] Add link to source code, write that as one of the features on the landing page
- [ ] Get PO box
- [ ] Make flyers?
- [x] Remove Your stories will be edited upon receiving. 
- [x] For story paragraphs add style: "f55-l f5"
- [x] Sign in should show up on mobile, sign out should not (it is replaced by profile)
- [x] Add POST for /profile
- [ ] Add database backup -dunl
- [x] add download route (/download/userid.json) userid "all" will return all published stories
- [ ] Add delete profile after profile stuff
- [x] Add prompts for deleting https://stackoverflow.com/questions/10462839/how-to-display-a-confirmation-dialog-when-clicking-an-a-link
- [x] No stories write one error message should link to the story topic.
- [x] add  formspree on contact page
- [x] Sitemap and RSS feed should link to anonfiction.com
- [x] Have a new page showing all the published stories, listed by their description https://cowyo.com/PilarPoolFrog/edit
- [x] Possibly missing </div> in header?
- [x] Missing </html> and </body>
- [x] Move "read" link on navigation to direct to /all
- [x] Fix the overlap in the double lines for /all
- [x] Remove the landing page stuff from /all
- [x] Add number of views per story (add "Views" into JSONStore)
- [ ] Generate a PDF of all published stories (leverage Latex)
- [x] Misson: Paying for stories is not longterm. The ideal is that people will "ready a story, leave a story." People are providing their stories to indulge others, which can be repayed by providing your own story. $3 rational: These stories need no fact checking, no research, as you are the sole authority. The stories are also short, so 500 words should only take 15 minutes or less. Thus $3 is about $12/hour which is a good price for a simple task that can be done by anyone.
